source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DQLoopBanner_Example', :exclusive => true do
  pod "DQLoopBanner", :path => "../"
end

target 'DQLoopBanner_Tests', :exclusive => true do
  pod "DQLoopBanner", :path => "../"

  
end
